name: ArchivalZip

on:
  push:
    branches:
      - main
    paths:
      - assets/**
      - pack.mcmeta

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        TOKEN: ${{ secrets.TOKEN }}

    - name: pull latest and remove old file from repo
      run: |
        git config --global user.name "clxrffdman"
        git config --global user.email "clxrffdman@gmail.com"
        git config pull.rebase false
        git pull
        rm -f release.zip

    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: new pack!
