name: ArchivalZip

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: pull latest and remove old file from repo
      run: |
        git config --global user.name "clxrffdman"
        git config --global user.email "clxrffdman@gmail.com"
        git config pull.rebase false
        git pull
        rm -f release.zip

    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'

    - name: Push changes to remote
      run: |
        git config --global user.name "clxrffdman"
        git config --global user.email "clxrffdman@gmail.com"
        git add -A
        git commit -m "new pack"
        git push