name: Archive and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: pull latest and remove old file from repo
      run: |
        git config --global user.name "clxrffdman"
        git config --global user.email "clxrffdman@gmail.com"
        git config pull.rebase false
        git pull
        rm -f release.zip

    - name: Archive Release
      run: |
        zip -r release.zip .
      working-directory: ${{ github.workspace }}
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: release-artifact
        path: release.zip

    - name: Push changes to main
      run: |
        git add -A
        git commit -m "Add release.zip"
        git push origin main

    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: release-artifact
        path: .

    - name: Push changes with release.zip to main
      run: |
        git add -A
        git commit -m "Add release.zip"
        git push origin main